name: gh-pages-deployment

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Update root README
        run: |
          for subdir in $(find . -mindepth 1 -maxdepth 1 -type d); do
            if [[ $subdir =~ ^\.\/\.github* ]] || [[ $subdir =~ ^\.\/\.git* ]]; then
              continue
            fi
            echo "- [$(basename $subdir)]($(basename $subdir))" >> $subdir/README.md
          done
        shell: bash

      - name: Update README
        run: |
          # Loop over all directories in the repository
          for dir in $(find . -type d); do
          
            # Skip irrelevant directories
            if [[ $dir == . ]] || [[ $dir =~ ^\.\/\.github* ]] || [[ $dir =~ ^\.\/\.git* ]]; then
              continue
            fi
          
            # Skip directories that do not contain subdirectories
            if [ -z "$(find "$dir" -mindepth 1 -maxdepth 1 -type d)" ]; then
              continue
            fi
          
            echo "[LOG] Processing directory: $dir"
          
            echo "## $dir" > $dir/README.md || echo "Failed to create README in $dir"
            echo "" >> $dir/README.md

            echo "[$(dirname $dir)]($(dirname $dir))" >> $dir/README.md
            for subdir in $(find $dir -mindepth 1 -maxdepth 1 -type d); do
              echo "- [$(basename $subdir)]($(basename $subdir))" >> $dir/README.md
            done
          
          done
        shell: bash

      - name: Publish current workdir (which contains generated content) to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3

        with:

          # Optional. Default value "." means the root directory of your project will be published.
          # You can use whatever directory your project uses, for example "wwwroot".
          # Such a directory does *not* have to already exist in your repo,
          # it could be an output directory created dynamically by your static website builder.
          source-directory: .

          # Optional. Default value "gh-pages".
          # It specifies the temporary branch which hosts the static website.
          # Each build will OVERWRITE this branch.
          target-branch: gh-pages
